### ISSUE TITLE
Explorer use incorrect syntax in table path

### ISSUE THREAD

**Issue by wbo2020** [JonathanTurnock/dcsfiddle#17]
Explorer is so convenience. but didn't function properly.

Viewing the mission table for example:
getMeta(_G.env.mission.coalition.blue.country.0)
LuaHooks (Main): [dcs-fiddle-server] - Failed to handle request due to [string dcs-fiddle-server.lua"]:264: [string "..."]

they should be 
_G.env.mission.coalition.blue.country[0]

Or
_G["env"]["mission"]["coalition"]["blue"]["country"][0]
_G["env"]["mission"]["theatre"]

Many other tables in Explorer were unviewable, most likely for the same reason.
getMeta(_G.db.Weapons.ByCLSID.{005E70F5-C3EA-4E95-A148-C1044C42D845})

_G.db.Weapons.ByCLSID["{005E70F5-C3EA-4E95-A148-C1044C42D845}"]
Or
_G["db"]["Weapons"]["ByCLSID"]["{005E70F5-C3EA-4E95-A148-C1044C42D845}"]

**Comment by JonathanTurnock** [comment]
Hey, does the recent development branch address these issues?

https://develop.dcsfiddle.pages.dev/
